# Generated by Django 2.2.11 on 2020-05-15 11:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restframework_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='charge',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='refund',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=jsonfield.fields.JSONField(),
        ),
    ]
